#!/bin/bash

# listing directories
alias l='ls -la' # detailed list, show hidden
alias lh='ls -lah' # detailed list, show hidden, human filesizes
alias ll='ls -lrth' # detailed list, no hidden
alias ls.='ls -d .[^.]*' # regular list, only hidden
alias ll.='ls -ld .[^.]*' # detailed list, only hidden
alias lsd='ls -d *(-/DN)' # regular list, only directories
alias lld='ls -ld *(-/DN)' # detailed list, only directories
  
# navigation
alias -- -='cd -'   # flip to last dir with just '-'

# pacman
alias pacman='sudo pacman'
  
# directories
alias md='mkdir -p'
alias rd='rmdir'
alias mounted="mount |column -t"
  
# size
alias du='du -shc'
alias df='df -h'
#alias d='dirs -v'   # list directory stack
#alias pu='pushd'
#alias po='popd'
#  alias -g ...='../..'
#  alias -g ....='../../..'
#  alias -g .....='../../../..'
# alias 1='cd -' # jump to 'n' in directory stack...
# alias 2='cd +2'
# alias 3='cd +3'
# alias 4='cd +4'
# alias 5='cd +5'
# alias 6='cd +6'
# alias 7='cd +7'
# alias 8='cd +8'
# alias 9='cd +9'

# gnupg alias
# alias encrypt='gpg -e -r me'
# alias decrypt='gpg --decrypt'
  

  # sound cards not using the same id @home/work
  # hades is my laptop littre name 
# if [ $HOST = "hades" ];then
#    alias alsamixer='alsamixer -c0'
# else
#    alias alsamixer='alsamixer -c1'
# fi
# 
# # browsers
# alias chrome='chromium --disable-extensions --incognito'
# 
# # screenshots
# alias sc="scrot 'screenshot-%d%m%Y_%H%M%S.png' -s -e 'mv screenshot* ~/tmp'"
# 
# # battery status
# alias battery='acpi -V | sed -n -e 1p -e 4p'
# 
# # calculator 
# alias calc="gcalccmd"
# 
# # git
# alias g='git'
alias gg='git log --graph --full-history --date=relative --color --pretty=format:"%C(yellow)%h  %C(cyan)%ad %Cgreen[ %aN ] %Creset%s %C(bold yellow)%d" --graph'
# alias gwc='git whatchanged'
# 
# alias gst='git status'
# alias gd='git diff'
# alias gds='git diff --staged'
# alias gb='git branch -a -v' # verbosely list local and remote branches
# alias ga='git add'
# alias gap='git add -p' # interactively add files to index
# alias gu='git unstage' # unstage file from index, defined in ~/.gitconfig
# alias gci='git commit'
# alias gco='git checkout'
# alias gf='git fetch'
# alias gm='git merge'
# alias gr='git rebase'
# # tomb
# alias sesame="pass open -f" 
# alias slam="pass close -f"
# alias insert="pass insert"
# alias passf="pass find"

# suffix aliases (for future zsh port)
# alias -s pdf='mupdf'
# alias -s svg='inkscape'
# alias -s avi='mplayer'
# alias -s mpg='mplayer'
# alias -s mov='mplayer'
# alias -s mkv='mplayer'
# alias -s doc='libreoffice'
# alias -s docx='libreoffice'
# alias -s odt='libreoffice'
# alias -s xls='libreoffice'
# alias -s ods='libreoffice'
# alias -s xlsx='libreoffice'
# alias -s ppt='libreoffice'
# alias -s jpg='imvr'
# alias -s jpeg='imvr'
# alias -s png='imvr'
