#!/usr/bin/env bash

source $HOME/.bash_profile

#xrdb ~/.Xresources
#setxkbmap dvorak -option ctrl:nocaps  

#sxhkd -m -1 &

#compton &
#autorandr -c

#dunst &
#unclutter &

feh --bg-scale Downloads/pexels-philippe-donn-1114690.jpg
xinput disable "Synaptics TM3053-004"

#udiskie -a -N &
#dwmstatus &

#test -x $(which syncthing) && syncthing -logfile=$HOME/.cache/syncthing.log &

# Start Shepherd to manage user daemons
#if [ -z "$(pgrep -u benoit shepherd)" ]; then
#  touch ~/started.pid
#  shepherd
#fi

test -p /tmp/dwm.fifo || (umask 077; mkfifo /tmp/dwm.fifo)
exec dbus-launch dwm
