#!/bin/bash

if [ -x /usr/bin/dircolors ]
then
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias cfg-i3="$EDITOR ~/.config/i3/config"
alias dvgrab="dvgrab myvideo- -s0 - | mpv -"

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias vi=vim

# listing directories
alias ls='ls --color=auto' # detailed list, show hidden
alias l='ls -la' # detailed list, show hidden
alias lh='ls -lah' # detailed list, show hidden, human filesizes
alias ll='ls -lrth' # detailed list, no hidden
alias ls.='ls -d .[^.]*' # regular list, only hidden
alias ll.='ls -ld .[^.]*' # detailed list, only hidden
alias lsd='ls -d *(-/DN)' # regular list, only directories
alias lld='ls -ld *(-/DN)' # detailed list, only directories

# path
alias path='echo -e ${PATH//:/\\n}'

# directory navigation
alias -- -='cd -'   # flip to last dir with just '-'
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'

alias pu='pushd'
alias po='popd'

alias d='dirs -v'   # list directory stack
alias cdd="pu +\$(d | fzy | awk '{print \$1}')"
alias 1='cd -' # jump to 'n' in directory stack...
alias 2='pu +2'
alias 3='pu +3'
alias 4='pu +4'
alias 5='pu +5'
alias 6='pu +6'
alias 7='pu +7'
alias 8='pu +8'
alias 9='pu +9'

# pacman
alias pacman='sudo pacman'

# directories
alias md='mkdir -p'
alias rd='rmdir'
alias mounted="mount |column -t"

# size
alias du='du -shc'
alias df='df -h'

# chezmoi
alias cmc="chezmoi diff -f git | grep -- ^--- | sed -e 's/^--- a\///' | grep -v /dev/null"

cmm() {
	pushd .
	cd ~
	cmc | xargs -r chezmoi merge
	popd
} && export -f cmm

# git
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gg='git log --graph --full-history --date=relative --color --pretty=format:"%C(yellow)%h  %C(cyan)%ad %Cgreen[ %aN ] %Creset%s %C(bold yellow)%d" --graph'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gr='git remote'
alias grs='git remote show'
alias co='git checkout $(git branch | fzy | sed "s|[ * ]*||")'
alias cor='git checkout $(git branch -r | fzy | sed -e "s|[ * ]*||" -e "s|origin/||")'

# info
alias battery='acpi -V | sed -n -e 1p -e 4p'
alias a="alias"

# surfing

alias ?='sr duckduckgo'
alias srd='sr duckduckgo'
alias ??='sr google'
alias srg='sr duckduckgo'

alias flameshot='flameshot gui -d 3'
# gnupg alias
# alias encrypt='gpg -e -r me'
# alias decrypt='gpg --decrypt'


# # screenshots
# alias sc="scrot 'screenshot-%d%m%Y_%H%M%S.png' -s -e 'mv screenshot* ~/tmp'"
#
# # calculator
# alias calc="gcalccmd"
#
# # tomb
# alias sesame="pass open -f"
# alias slam="pass close -f"
# alias insert="pass insert"
# alias passf="pass find"
alias barney-fan='ssh barney "sudo -S /root/ipmi.sh"'

alias reconfigure='sudo -E guix system reconfigure ~/.config/guix/system/config.scm'
alias ncspot="TERM=xterm ncspot"

alias tesseract="TESSDATA_PREFIX=$HOME/src/others/tessdata tesseract"
